[package]
name = "odin"
version = "0.1.0"
authors = ["Meenakshi Sundaram V <vms20591@riseup.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "1.9.3"
clap = "2.33.1"